// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
public sealed partial class Migration_19 : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_19));
    
    string IMigrationMetadata.Id
    {
        get { return "201702162311176_Migration_19"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
