// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
public sealed partial class TablaMonitoreoSesion : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(TablaMonitoreoSesion));
    
    string IMigrationMetadata.Id
    {
        get { return "202107162157135_TablaMonitoreoSesion"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
