// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
public sealed partial class DeIntALongFolio : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(DeIntALongFolio));
    
    string IMigrationMetadata.Id
    {
        get { return "202110270625526_DeIntALongFolio"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return Resources.GetString("Source"); }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
