using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;


//public enum CuentaContable
//{
//    [Display(Name = "Disponible")]
//    Disponible = 1220010,
//    [Display(Name = "Bancos")]
//    Bancos = 1220020,
//    [Display(Name = "Depósitos a Plazo")]
//    DepositosAPlazo = 1220030,
//    [Display(Name = "Valores Negociables (neto)")]
//    ValoresNegociables = 1220040,
//    [Display(Name = "Deudores Por Venta (neto)")]
//    DeudoresPorVenta = 1220050,
//    [Display(Name = "Documentos Por Cobrar (neto)")]
//    DocumentosPorCobrar = 1220060,
//    [Display(Name = "Deudores Varios (neto)")]
//    DeudoresVarios = 1220070,
//    [Display(Name = "Anticipos remuneraciones")]
//    AnticiposRemuneraciones = 1220071,
//    [Display(Name = "Documentos y Cuentas Por Cobrar a Empresas Relacionadas")]
//    DocumentosyCuentasPorCobrarAEmpresasRelacionadas = 1220080,
//    [Display(Name = "Cta Corriente Agencia o Establecimiento Permanente en el Exterior")]
//    CtaCorrienteAgenciaoEstablecimientoPermanenteEnElExterior = 1220090,
//    [Display(Name = "Existencias (neto)")]
//    Existencias = 1220100,
//    [Display(Name = "Impuestos por recuperar")]
//    ImpuestosPorRecuperar = 1220110,
//    [Display(Name = "IVA Créditos")]
//    IVACréditos = 1220111,
//    [Display(Name = "Gastos Pagados Por Anticipado")]
//    GastosPagadosPorAnticipado = 1220120,
//    [Display(Name = "Impuesto Diferido Activo")]
//    ImpuestoDiferidoActivo = 1220130,
//    [Display(Name = "Otras activos circulantes")]
//    OtrasActivosCirculantes = 1220140,
//    [Display(Name = "Contratos Leasing (neto)")]
//    ContratosLeasing = 1220150,
//    [Display(Name = "Activos para Leasing (neto)")]
//    ActivosParaLeasing = 1220160,
//    [Display(Name = "Terrenos")]
//    Terrenos = 647010,
//    [Display(Name = "Construcciones y Obras de Infraestructuras")]
//    ConstruccionesyObrasDeInfraestructuras = 647020,
//    [Display(Name = "Obras en construcción")]
//    ObrasEnConstrucción = 647021,
//    [Display(Name = "Maquinarias y Equipos")]
//    MaquinariasyEquipos = 647030,
//    [Display(Name = "Activos en Leasing")]
//    ActivosEnLeasing = 647040,
//    [Display(Name = "Otros activos Fijos")]
//    OtrosActivosFijos = 647050,
//    [Display(Name = "Mayor Valor Retasación técnica del activo Fijo")]
//    MayorValorRetasaciónTécnicaDelActivoFijo = 647060,
//    [Display(Name = "Depreciación Acumulada")]
//    DepreciaciónAcumulada = 647070,
//    [Display(Name = "Inversión en Empresas Relacionadas Nacional")]
//    InversiónEnEmpresasRelacionadasNacional = 1221010,
//    [Display(Name = "Inversión en Empresas Relacionadas Extranjera")]
//    InversiónEnEmpresasRelacionadasExtranjera = 1221020,
//    [Display(Name = "Inversión En Otras Sociedades")]
//    InversiónEnOtrasSociedades = 1221030,
//    [Display(Name = "Inversión en agencias o establecimiento permanente en el Exterior")]
//    InversiónEnAgenciasoEstablecimientoPermanenteEnElExterior = 1221040,
//    [Display(Name = "Menor valor Inversiones")]
//    MenorValorInversiones = 1221050,
//    [Display(Name = "Mayor Valor Inversiones")]
//    MayorValorInversiones = 1221060,
//    [Display(Name = "Deudores a largo plazo")]
//    DeudoresaLargoPlazo = 1221070,
//    [Display(Name = "Documentos y Cuentas Por cobrar a Empresas Relacionadas largo plazo")]
//    DocumentosyCuentasPorCobrarAEmpresasRelacionadasLargoPlazo = 1221080,
//    [Display(Name = "Impuestos Diferidos de largo plazo")]
//    ImpuestosDiferidosDeLargoPlazo = 1221090,
//    [Display(Name = "Intangibles")]
//    Intangibles = 1221100,
//    [Display(Name = "Amortización")]
//    Amortización = 1221110,
//    [Display(Name = "Otros Activos")]
//    OtroActivos = 1221120,
//    [Display(Name = "Contratos de leasing largo plazo (neto)")]
//    ContratosDeLeasingLargoPlazo = 1221130,
//    [Display(Name = "Obligaciones con bancos e Instituciones Financieras corto plazo")]
//    ObligacionesConBancoseInstitucionesFinancierasCortoPlazo = 1230010,
//    [Display(Name = "Obligaciones con bancos e Instituciones Financieras LP -porción corto plazo")]
//    ObligacionesConBancoseInstitucionesFinancierasLPPorciónCortoPlazo = 1230020,
//    [Display(Name = "Obligaciones con el público (pagarés )")]
//    Pagares = 1230030,
//    [Display(Name = "Obligaciones con el público - porción corto plazo (bonos)")]
//    Bonos = 1230040,
//    [Display(Name = "Obligaciones largo plazo con vencimiento dentro de un año")]
//    ObligacionesLargoPlazoConVencimientoDentroDeUnAño = 1230050,
//    [Display(Name = "Dividendo por pagar")]
//    DividendoPorPagar = 1230060,
//    [Display(Name ="Cuentas y Documentos por pagar")]
//    CuentasyDocumentosPorPagar = 1230070,
//    [Display(Name = "Acreedores varios")]
//    AcreedoresVarios = 1230090,
//    [Display(Name = "Obligaciones o Acreedores por Leasing porción corto plazo")]
//    ObligacionesoAcreedoresPorLeasingPorciónCortoPlazo = 1230100,
//    [Display(Name = "Documentos y cuentas por pagar empresas relacionadas")]
//    DocumentosyCuentasPorPagarEmpresasRelacionadas = 1230110,
//    [Display(Name = "Cta Cte Agencia o Establecimiento Permanente en el Exterior")]
//    CtaCteAgenciaoEstablecimientoPermanenteEnElExterior2 = 1230120,
//    [Display(Name = "Provisiones")]
//    Provisiones = 1230130,
//    [Display(Name = "Retenciones")]
//    Retenciones = 1230140,
//    [Display(Name = "Impuesto a la renta")]
//    ImpuestoALaRenta = 1230150,
//    [Display(Name = "Ingresos percibidos por adelantados")]
//    IngresosPercibidosPorAdelantados = 1230160,
//    [Display(Name = "Impuestos Diferidos Pasivo")]
//    ImpuestosDiferidosPasivo = 1230170,
//    [Display(Name = "IVA Débitos")]
//    IVADébitos = 1220171,
//    [Display(Name = "Otros pasivos circulantes")]
//    OtrosPasivosCirculantes = 1230180,
//    [Display(Name = "Obligaciones con bancos e Instituciones Financieras")]
//    ObligacionesConBancoseInstitucionesFinancieras = 1231010,
//    [Display(Name = "Obligaciones con el público Largo Plazo (Bonos)")]
//    BonosPublico = 1231020,
//    [Display(Name = "Documentos por Pagar largo plazo")]
//    DocumentosPorPagarLargoPlazo = 1231030,
//    [Display(Name = "Acreedores Varios Largo Plazo")]
//    AcreedoresVariosLargoPlazo = 1231040,
//    [Display(Name = "Obligaciones o Acreedores por Leasing porción largo plazo")]
//    ObligacionesoAcreedoresPorLeasingPorciónLargoPlazo = 1231050,
//    [Display(Name = "Documentos y Cuentas Por Pagar a Empresas Relacionadas Largo Plazo")]
//    DocumentosyCuentasPorPagarAEmpresasRelacionadasLargoPlazo = 1231060,
//    [Display(Name = "Cta Cte Agencia o Establecimiento Permanente en el Exterior2")]
//    CtaCteAgenciaoEstablecimientoPermanenteEnElExterior1 = 1231070,
//    [Display(Name = "Provisiones largo plazo")]
//    ProvisionesLargoPlazo = 1231080,
//    [Display(Name = "Impuestos diferidos a largo plazo")]
//    ImpuestosDiferidosALargoPlazo = 1231090,
//    [Display(Name = "Otros pasivos a largo plazo")]
//    OtrosPasivosALargoPlazo = 1231100,
//    [Display(Name = "Otros pasivos")]
//    OtrosPasivos = 1231101,
//    [Display(Name = "Capital pagado")]
//    CapitalPagado = 1232010,
//    [Display(Name = "Reserva Revalorización Capital")]
//    ReservaRevalorizaciónCapital = 1232020,
//    [Display(Name = "Sobreprecio en venta de acciones propias")]
//    SobreprecioEnVentaDeAccionesPropias = 1232030,
//    [Display(Name = "Otras reservas")]
//    OtrasReservas = 1232040,
//    [Display(Name = "Utilidades retenidas o perdidas acumuladas")]
//    UtilidadesRetenidasoPerdidasAcumuladas = 1232051,
//    [Display(Name = "Utilidad o perdida del ejercicio")]
//    UtilidadoPerdidaDelEjercicio = 1232061,
//    [Display(Name = "Ingreso por ventas de bienes del giro a empresas no relacionadas del extranjero")]
//    IngresoPorVentasDeBienesDelGiroAEmpresasNoRelacionadasDelExtranjero = 628010,
//    [Display(Name = "Ingreso por ventas de bienes del giro a empresas relacionadas del extranjero")]
//    IngresoPorVentasDeBienesDelGiroAEmpresasRelacionadasDelExtranjero = 628020,
//    [Display(Name = "Ingreso por servicios del giro a empresas no relacionadas del extranjero")]
//    IngresoPorServiciosDelGiroAEmpresasNoRelacionadasDelExtranjero = 628030,
//    [Display(Name = "Ingreso por servicios del giro a empresas relacionadas del extranjero")]
//    IngresoPorServiciosDelGiroAEmpresasRelacionadasDelExtranjero = 628040,
//    [Display(Name = "Ingreso por ventas de bienes del giro a empresas no relacionadas del país")]
//    IngresoPorVentasDeBienesDelGiroAEmpresasNoRelacionadasDelPaís = 628050,
//    [Display(Name = "Ingreso por ventas de bienes del giro a empresas relacionadas del país")]
//    IngresoPorVentasDeBienesDelGiroAEmpresasRelacionadasDelPaís = 628060,
//    [Display(Name = "Ingreso por servicios del giro a empresas no relacionadas del país")]
//    IngresoPorServiciosDelGiroAEmpresasNoRelacionadasDelPaís = 628070,
//    [Display(Name = "Ingreso por servicios del giro a empresas relacionadas del país")]
//    IngresoPorServiciosDelGiroAEmpresasRelacionadasDelPaís = 628080,
//    [Display(Name = "Ingreso por venta de acciones (cuando son ventas del giro)")]
//    IngresoPorVentaDeAcciones = 628090,
//    [Display(Name = "Ingreso percibidos o devengados por Agencias o Establecimientos Permanentes en el Exterior")]
//    IngresoPercibidosoDevengadosPorAgenciasOEstablecimientosPermanentesEnElExterior = 628100,
//    [Display(Name = "Otros Ingresos del giro")]
//    OtrosIngresosDelGiro = 628110,
//    [Display(Name = "Intereses y/o Reajuste por Inversiones en depósitos a plazo y Capitales Mobiliarios")]
//    InteresesyoReajustePorInversionesEnDepositosAPlazoyCapitalesMobiliarios = 629010,
//    [Display(Name = "Utilidad en Operaciones con instrumentos derivados (Forwards, Opciones, etc)")]
//    UtilidadEnOperacionesConInstrumentosDerivados = 629020,
//    [Display(Name = "Intereses y/o Reajustes por préstamos a empresas no relacionadas del extranjero")]
//    InteresesyoReajustesPorPréstamosAEmpresasNoRelacionadasDelExtranjero = 629030,
//    [Display(Name = "Intereses y/o Reajustes por préstamos a empresas relacionadas del extranjero")]
//    InteresesyoReajustesPorPrestamosAEmpresasRelacionadasDelExtranjero = 629040,
//    [Display(Name = "Intereses y/o Reajustes por préstamos a empresas no relacionadas del país")]
//    InteresesyoReajustesPorPrestamosAEmpresasNoRelacionadasDelPais = 629050,
//    [Display(Name = "Intereses y/o Reajustes por préstamos a empresas relacionadas del país")]
//    InteresesyoReajustesPorPrestamosAEmpresasRelacionadasDelPais = 629060,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas no relacionadas del extranjero")]
//    InteresesyoReajustesPorOperacionesAEmpresasNoRelacionadasDelExtranjero1 = 629070,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas relacionadas del extranjero")]
//    InteresesyoReajustesPorOperacionesAEmpresasRelacionadasDelExtranjero1 = 629080,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas no relacionadas del país")]
//    InteresesyoReajustesPorOperacionesAEmpresasNoRelacionadasDelPais = 629090,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas relacionadas del país")]
//    InteresesyoReajustesPorOperacionesAEmpresasRelacionadasDelPais1 = 629100,
//    [Display(Name = "Intereses y/o Reajuste de bienes entregados en leasing")]
//    InteresesyoReajusteDeBienesEntregadosEnLeasing = 629110,
//    [Display(Name = "Intereses percibidos o devengados por Agencias o Establecimientos Permanentes en el Exterior")]
//    InteresesPercibidosoDevengadosPorAgenciasoEstablecimientosPermanentesEnElExterior = 629120,
//    [Display(Name = "Otros Intereses percibidos o devengados")]
//    OtrosInteresesPercibidosoDevengados = 629130,
//    [Display(Name = "Ingreso por venta de Acciones (ventas ocasionales) a empresas no relacionadas del extranjero")]
//    IngresoPorVentaDeAccionesAEmpresasNoRelacionadasDelExtranjero = 651010,
//    [Display(Name = "Ingreso por venta de Acciones (ventas ocasionales) a empresas relacionadas del extranjero")]
//    IngresoPorVentaDeAccionesAEmpresasRelacionadasDelExtranjero = 651020,
//    [Display(Name = "Ingreso por venta de Acciones (ventas ocasionales) a empresas no relacionadas del país")]
//    IngresoPorVentaDeAccionesAEmpresasNoRelacionadasDelPais = 651030,
//    [Display(Name = "Ingreso por venta de Acciones (ventas ocasionales) a empresas relacionadas del país")]
//    IngresoPorVentaDeAccionesAEmpresasRelacionadasDelPais = 651040,
//    [Display(Name = "Ingreso por venta de Derechos Sociales a empresas no relacionadas del extranjero")]
//    IngresoPorVentaDeDerechosSocialesAEmpresasNoRelacionadasDelExtranjero = 651050,
//    [Display(Name = "Ingreso por venta de Derechos Sociales a empresas relacionadas del extranjero")]
//    IngresoPorVentaDeDerechosSocialesAEmpresasRelacionadasDelExtranjero = 651060,
//    [Display(Name = "Ingreso por venta de Derechos Sociales a empresas no relacionadas del país")]
//    IngresoPorVentaDeDerechosSocialesAEmpresasNoRelacionadasDelPais = 651070,
//    [Display(Name = "Ingreso por venta de Derechos Sociales a empresas relacionadas del país")]
//    IngresoPorVentaDeDerechosSocialesAEmpresasRelacionadasDelPais = 651080,
//    [Display(Name = "Ingreso por venta de Activos Fijos a empresas no relacionadas del extranjero")]
//    IngresoPorVentaDeActivosFijosAEmpresasNoRelacionadasDelExtranjero = 651090,
//    [Display(Name = "Ingreso por venta de Activos Fijos a empresas relacionadas del extranjero")]
//    IngresoPorVentadeActivosFijosAEmpresasRelacionadasDelExtranjero = 651100,
//    [Display(Name = "Ingreso por venta de Activos Fijos a empresas no relacionadas del país")]
//    IngresoPorVentaDeActivosFijosAEmpresasNoRelacionadasDelPais = 651110,
//    [Display(Name = "Ingreso por venta de Activos Fijos a empresas relacionadas del país")]
//    IngresoPorVentaDeActivosFijosAEmpresasRelacionadasDelPais = 651120,
//    [Display(Name = "Ingreso por venta de Activos Fijos en Leasing")]
//    IngresoPorVentaDeActivosFijosEnLeasing = 651130,
//    [Display(Name = "Dividendos percibidos")]
//    DividendosPercibidos = 651140,
//    [Display(Name = "Ingreso por Impuesto recuperado por Utilidades Propias")]
//    IngresoPorImpuestoRecuperadoPorUtilidadesPropias = 651150,
//    [Display(Name = "Ingreso por Impuesto recuperado por Utilidades Ajenas")]
//    IngresoPorImpuestoRecuperadoPorUtilidadesAjenas = 651160,
//    [Display(Name = "Otros Ingresos percibidos o devengados por Agencias o Establecimientos Permanentes en el Exterior")]
//    OtrosIngresosPercibidosoDevengadosPorAgenciasoEstablecimientosPermanentesEnElExterior = 651170,
//    [Display(Name = "Otros Ingresos percibidos o devengados")]
//    OtrosIngresosPercibidosoDevengados = 651180,
//    [Display(Name = "Ingresos por Corrección Monetaria Financiera")]
//    IngresosPorCorrecciónMonetariaFinanciera = 651190,
//    [Display(Name = "Costo Directo por ventas de bienes del giro a empresas no relacionadas del extranjero")]
//    CostoDirectoPorVentasDeBienesDelGiroAEmpresasNoRelacionadasDelExtranjero = 630010,
//    [Display(Name = "Costo Directo por ventas de bienes del giro a empresas relacionadas del extranjero")]
//    CostoDirectoPorVentasDeBienesDelGiroAEmpresasRelacionadasDelExtranjero = 630020,
//    [Display(Name = "Costo Directo por servicios del giro a empresas no relacionadas del extranjero")]
//    CostoDirectoPorServiciosDelGiroAEmpresasNoRelacionadasDelExtranjero = 630030,
//    [Display(Name = "Costo Directo por servicios del giro a empresas relacionadas del extranjero")]
//    CostoDirectoPorServiciosDelGiroAEmpresasRelacionadasDelExtranjero = 630040,
//    [Display(Name = "Costo Directo por ventas de bienes del giro a empresas no relacionadas del país")]
//    CostoDirectoPorVentasDeBienesDelGiroAEmpresasNoRelacionadasDelPais = 630050,
//    [Display(Name = "Costo Directo por ventas de bienes del giro a empresas relacionadas del país")]
//    CostoDirectoPorVentasDeBienesDelGiroAEmpresasRelacionadasDelPais = 630060,
//    [Display(Name = "Costo Directo por servicios del giro a empresas no relacionadas del país")]
//    CostoDirectoPorServiciosDelGiroAEmpresasNoRelacionadasDelPais = 630070,
//    [Display(Name = "Costo Directo por servicios del giro a empresas relacionadas del país")]
//    CostoDirectoPorServiciosDelGiroAEmpresasRelacionadasDelPais = 630080,
//    [Display(Name = "Costo Directo por venta de acciones (cuando son ventas del giro)")]
//    CostoDirectoPorVentaDeAcciones = 630090,
//    [Display(Name = "Mermas de mercaderías, castigos y obsolescencias")]
//    MermasDeMercaderíasCastigosyObsolescencias = 630100,
//    [Display(Name = "Costo Directo de los bienes y servicios por Agencias o Establecimientos Permanentes en el Exterior")]
//    CostoDirectoDeLosBienesyServiciosPorAgenciasoEstablecimientosPermanentesEnElExterior = 630110,
//    [Display(Name = "Otros Costos Directos del giro")]
//    OtrosCostosDirectosDelGiro = 630120,
//    [Display(Name = "Resultado por Venta de Activos Fijos")]
//    ResultadoPorVentaDeActivosFijos1 = 630121,
//    [Display(Name = "Remuneraciones Imponibles y no Imponibles en el país")]
//    RemuneracionesImponiblesyNoImponiblesEnElPais = 631010,
//    [Display(Name = "Honorarios, excepto asesorías técnicas en el extranjero")]
//    HonorariosExceptoAsesoriasTecnicasEnElExtranjero = 631020,
//    [Display(Name = "Provisión Indemnización por años de servicio")]
//    ProvisiónIndemnizaciónPorAñosDeServicio = 631030,
//    [Display(Name = "Remuneraciones por Agencias o Establecimientos Permanentes en el Exterior")]
//    RemuneracionesPorAgenciasoEstablecimientosPermanentesEnElExterior = 631040,
//    [Display(Name = "Depreciación Activo Fijo")]
//    DepreciaciónActivoFijo = 632010,
//    [Display(Name = "Depreciación de automóviles y similares")]
//    DepreciaciónDeAutomóvilesySimilares = 632020,
//    [Display(Name = "Depreciación por diferencia en bienes con Retasación Técnica")]
//    DepreciaciónPorDiferenciaEnBienesConRetasacionTecnica = 632030,
//    [Display(Name = "Depreciación Activo en leasing")]
//    DepreciaciónActivoEnLeasing = 632040,
//    [Display(Name = "Depreciación por Agencias o Establecimientos Permanentes en el Exterior")]
//    DepreciaciónPorAgenciasoEstablecimientosPermanentesEnElExterior = 632050,
//    [Display(Name = "Otras Depreciaciones")]
//    OtrasDepreciaciones = 632060,
//    [Display(Name = "Intereses y/o Reajuste por Inversiones en depósitos a plazo y Capitales Mobiliarios")]
//    InteresesyoReajustePorInversionesEnDepositosAPlazoyCapitalesMobiliarios1 = 633010,
//    [Display(Name = "Pérdidas en Operaciones con instrumentos derivados (Forwards, Opciones, etc)")]
//    PérdidasEnOperacionesConInstrumentosDerivados = 633020,
//    [Display(Name = "Intereses y/o Reajustes por préstamos con empresas no relacionadas del extranjero")]
//    InteresesyoReajustesPorPrestamosConEmpresasNoRelacionadasDelExtranjero = 633030,
//    [Display(Name = "Intereses y/o Reajustes por préstamos con empresas relacionadas del extranjero")]
//    InteresesyoReajustesPorPrestamosConEmpresasRelacionadasDelExtranjero = 633040,
//    [Display(Name = "Intereses y/o Reajustes por préstamos con empresas no relacionadas del país")]
//    InteresesyoReajustesPorPrestamosConEmpresasNoRelacionadasDelPais = 633050,
//    [Display(Name = "Intereses y/o Reajustes por préstamos con empresas relacionadas del país")]
//    InteresesyoReajustesPorPrestamosConEmpresasRelacionadasDelPais = 633060,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas no relacionadas del extranjero")]
//    InteresesyoReajustesPorOperacionesAEmpresasNoRelacionadasDelExtranjero = 633070,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas relacionadas del extranjero")]
//    InteresesyoReajustesPorOperacionesAEmpresasRelacionadasDelExtranjero = 633080,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas no relacionadas del país")]
//    InteresesyoReajustesPorOperacionesAEmpresasNoRelacionadasDelPais1 = 633090,
//    [Display(Name = "Intereses y/o Reajustes por operaciones a empresas relacionadas del país")]
//    InteresesyoReajustesPorOperacionesAEmpresasRelacionadasDelPais = 633100,
//    [Display(Name = "Intereses pagados o adeudados por Agencias o Establecimientos Permanentes en el Exterior")]
//    InteresesPagadosoAdeudadosPorAgenciasoEstablecimientosPermanentesEnElExterior = 633110,
//    [Display(Name = "Otros Intereses pagados o adeudados")]
//    OtrosInteresesPagadosoAdeudados = 633120,
//    [Display(Name = "Costo de Venta de Acciones (ventas ocasionales)")]
//    CostoDeVentaDeAccionesOcasionales = 635010,
//    [Display(Name = "Resultado por Venta de Activos en Leasing")]
//    ResultadoPorVentaDeActivosEnLeasing = 635031,
//    [Display(Name = "Resultado por Venta de Activos Fijos")]
//    ResultadoPorVentaDeActivosFijos = 635041,
//    [Display(Name = "Costo en Adquisición de Derechos por cesión de Contratos Leasing")]
//    CostoEnAdquisiciónDeDerechosPorCesiónDeContratosLeasing = 635040,
//    [Display(Name = "Costo de Venta de Derechos Sociales")]
//    CostoDeVentaDeDerechosSociales = 635050,
//    [Display(Name = "Pérdidas y Ganancias por Impuestos Diferidos")]
//    PerdidasyGananciasPorImpuestosDiferidos = 635061,
//    [Display(Name = "Obsolescencia de Bienes del Activo Inmovilizado")]
//    ObsolescenciaDeBienesDelActivoInmovilizado = 635080,
//    [Display(Name = "Pérdida y ganancia en empresas relacionadas VPP (normas financieras)")]
//    PerdidayGananciaEnEmpresasRelacionadasVPP = 635090,
//    [Display(Name = "Pérdida y ganancias en Operaciones de Leasing o Leaseback")]
//    PerdidayGananciasEnOperacionesDeLeasingoLeaseback = 635100,
//    [Display(Name = "Pérdida y ganancias en Operaciones de Forward, Futuros y Operaciones de Tipo de Cambio")]
//    PerdidayGananciasEnOperacionesDeForwardFuturosyOperacionesDeTipoDeCambio = 635110,
//    [Display(Name = "Perdida y ganancias en Patentes, marcas, royalties y asesorías generales a empresas no relacionadas")]
//    PerdidayGananciasEnPatentesMarcasRoyaltiesyAsesoriasGeneralesAEmpresasNoRelacionadas = 635120,
//    [Display(Name = "Perdida y ganancias en Patentes, marcas, royalties y Asesorías generales a empresas relacionadas")]
//    PerdidayGananciasEnPatentesMarcasRoyaltiesyAsesoriasGeneralesAEmpresasRelacionadas = 635130,
//    [Display(Name = "Asesorías Técnicas en el extranjero")]
//    AsesoriasTecnicasEnElExtranjero = 635140,
//    [Display(Name = "Pérdida por ajustes a valor de mercado (Ej Val Negociables, Fondos Mutuos)")]
//    PerdidaPorAjustesAValorDeMercado = 635150,
//    [Display(Name = "Deudores Incobrables")]
//    DeudoresIncobrables = 635160,
//    [Display(Name = "Perdida por Corrección Monetaria Financiera")]
//    PerdidaPorCorreccionMonetariaFinanciera = 635171,
//    [Display(Name = "Otros gastos deducidos de los ingresos brutos por Agencias o Establecimientos Permanentes en el Exterior")]
//    OtrosGastosDeducidosDeLosIngresosBrutosPorAgenciasoEstablecimientosPermanentesEnElExterior = 635180,
//    [Display(Name = "Gastos de administración y ventas")]
//    GastosDeAdministraciónyVentas = 635181,
//    [Display(Name = "Otros gastos deducidos de los ingresos brutos")]
//    OtrosGastosDeducidosDeLosIngresosBrutos = 635190,
//    [Display(Name = "Distribución de utilidades")]
//    DistribucionDeUtilidades = 635201,
//    [Display(Name = "Retiros de socios")]
//    RetirosDeSocios = 635202,
//    [Display(Name = "Aportes de socios")]
//    AportesDeSocios = 635203,
//    [Display(Name = "Otras cuentas de pérdidas")]
//    OtrasCuentasDePerdidas = 635210,
//    [Display(Name = "Otras cuentas de ganancias")]
//    OtrasCuentasDeGanancias = 635211,
//    [Display(Name = "Cuentas de Orden")]
//    CuentasDeOrden = 710010
//}
