//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sii.cl/SiiDte")]
[System.Xml.Serialization.XmlRootAttribute("DTE", Namespace="http://www.sii.cl/SiiDte", IsNullable=false)]
public partial class DTEDefType {
    
    private DTEDefTypeExportaciones itemField;
    
    private decimal versionField;
    
    public DTEDefType() {
        this.versionField = ((decimal)(1.0m));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Exportaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportaciones Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportaciones {
    
    private DTEDefTypeExportacionesEncabezado encabezadoField;
    
    private DTEDefTypeExportacionesDetalle[] detalleField;
    
    private DTEDefTypeExportacionesSubTotInfo[] subTotInfoField;
    
    private DTEDefTypeExportacionesDscRcgGlobal[] dscRcgGlobalField;
    
    private DTEDefTypeExportacionesReferencia[] referenciaField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezado Encabezado {
        get {
            return this.encabezadoField;
        }
        set {
            this.encabezadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Detalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalle[] Detalle {
        get {
            return this.detalleField;
        }
        set {
            this.detalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubTotInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesSubTotInfo[] SubTotInfo {
        get {
            return this.subTotInfoField;
        }
        set {
            this.subTotInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DscRcgGlobal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDscRcgGlobal[] DscRcgGlobal {
        get {
            return this.dscRcgGlobalField;
        }
        set {
            this.dscRcgGlobalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Referencia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesReferencia[] Referencia {
        get {
            return this.referenciaField;
        }
        set {
            this.referenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezado {
    
    private DTEDefTypeExportacionesEncabezadoIdDoc idDocField;
    
    private DTEDefTypeExportacionesEncabezadoEmisor emisorField;
    
    private DTEDefTypeExportacionesEncabezadoReceptor receptorField;
    
    private DTEDefTypeExportacionesEncabezadoTransporte transporteField;
    
    private DTEDefTypeExportacionesEncabezadoTotales totalesField;
    
    private DTEDefTypeExportacionesEncabezadoOtraMoneda otraMonedaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoIdDoc IdDoc {
        get {
            return this.idDocField;
        }
        set {
            this.idDocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoEmisor Emisor {
        get {
            return this.emisorField;
        }
        set {
            this.emisorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoReceptor Receptor {
        get {
            return this.receptorField;
        }
        set {
            this.receptorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoTransporte Transporte {
        get {
            return this.transporteField;
        }
        set {
            this.transporteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoTotales Totales {
        get {
            return this.totalesField;
        }
        set {
            this.totalesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoOtraMoneda OtraMoneda {
        get {
            return this.otraMonedaField;
        }
        set {
            this.otraMonedaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoIdDoc {
    
    private EXPType tipoDTEField;
    
    private string folioField;
    
    private System.DateTime fchEmisField;
    
    private DTEDefTypeExportacionesEncabezadoIdDocTipoDespacho tipoDespachoField;
    
    private bool tipoDespachoFieldSpecified;
    
    private DTEDefTypeExportacionesEncabezadoIdDocIndServicio indServicioField;
    
    private bool indServicioFieldSpecified;
    
    private DTEDefTypeExportacionesEncabezadoIdDocFmaPago fmaPagoField;
    
    private bool fmaPagoFieldSpecified;
    
    private string fmaPagExpField;
    
    private System.DateTime fchCancelField;
    
    private bool fchCancelFieldSpecified;
    
    private string mntCancelField;
    
    private string saldoInsolField;
    
    private DTEDefTypeExportacionesEncabezadoIdDocMntPagos[] mntPagosField;
    
    private System.DateTime periodoDesdeField;
    
    private bool periodoDesdeFieldSpecified;
    
    private System.DateTime periodoHastaField;
    
    private bool periodoHastaFieldSpecified;
    
    private MedioPagoType medioPagoField;
    
    private bool medioPagoFieldSpecified;
    
    private DTEDefTypeExportacionesEncabezadoIdDocTpoCtaPago tpoCtaPagoField;
    
    private bool tpoCtaPagoFieldSpecified;
    
    private string numCtaPagoField;
    
    private string bcoPagoField;
    
    private string termPagoCdgField;
    
    private string termPagoGlosaField;
    
    private string termPagoDiasField;
    
    private System.DateTime fchVencField;
    
    private bool fchVencFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EXPType TipoDTE {
        get {
            return this.tipoDTEField;
        }
        set {
            this.tipoDTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string Folio {
        get {
            return this.folioField;
        }
        set {
            this.folioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchEmis {
        get {
            return this.fchEmisField;
        }
        set {
            this.fchEmisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoIdDocTipoDespacho TipoDespacho {
        get {
            return this.tipoDespachoField;
        }
        set {
            this.tipoDespachoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TipoDespachoSpecified {
        get {
            return this.tipoDespachoFieldSpecified;
        }
        set {
            this.tipoDespachoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoIdDocIndServicio IndServicio {
        get {
            return this.indServicioField;
        }
        set {
            this.indServicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndServicioSpecified {
        get {
            return this.indServicioFieldSpecified;
        }
        set {
            this.indServicioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoIdDocFmaPago FmaPago {
        get {
            return this.fmaPagoField;
        }
        set {
            this.fmaPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FmaPagoSpecified {
        get {
            return this.fmaPagoFieldSpecified;
        }
        set {
            this.fmaPagoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string FmaPagExp {
        get {
            return this.fmaPagExpField;
        }
        set {
            this.fmaPagExpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchCancel {
        get {
            return this.fchCancelField;
        }
        set {
            this.fchCancelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FchCancelSpecified {
        get {
            return this.fchCancelFieldSpecified;
        }
        set {
            this.fchCancelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")]
    public string MntCancel {
        get {
            return this.mntCancelField;
        }
        set {
            this.mntCancelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")]
    public string SaldoInsol {
        get {
            return this.saldoInsolField;
        }
        set {
            this.saldoInsolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MntPagos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoIdDocMntPagos[] MntPagos {
        get {
            return this.mntPagosField;
        }
        set {
            this.mntPagosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime PeriodoDesde {
        get {
            return this.periodoDesdeField;
        }
        set {
            this.periodoDesdeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeriodoDesdeSpecified {
        get {
            return this.periodoDesdeFieldSpecified;
        }
        set {
            this.periodoDesdeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime PeriodoHasta {
        get {
            return this.periodoHastaField;
        }
        set {
            this.periodoHastaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PeriodoHastaSpecified {
        get {
            return this.periodoHastaFieldSpecified;
        }
        set {
            this.periodoHastaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MedioPagoType MedioPago {
        get {
            return this.medioPagoField;
        }
        set {
            this.medioPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MedioPagoSpecified {
        get {
            return this.medioPagoFieldSpecified;
        }
        set {
            this.medioPagoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoIdDocTpoCtaPago TpoCtaPago {
        get {
            return this.tpoCtaPagoField;
        }
        set {
            this.tpoCtaPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpoCtaPagoSpecified {
        get {
            return this.tpoCtaPagoFieldSpecified;
        }
        set {
            this.tpoCtaPagoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NumCtaPago {
        get {
            return this.numCtaPagoField;
        }
        set {
            this.numCtaPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BcoPago {
        get {
            return this.bcoPagoField;
        }
        set {
            this.bcoPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TermPagoCdg {
        get {
            return this.termPagoCdgField;
        }
        set {
            this.termPagoCdgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TermPagoGlosa {
        get {
            return this.termPagoGlosaField;
        }
        set {
            this.termPagoGlosaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string TermPagoDias {
        get {
            return this.termPagoDiasField;
        }
        set {
            this.termPagoDiasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchVenc {
        get {
            return this.fchVencField;
        }
        set {
            this.fchVencField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FchVencSpecified {
        get {
            return this.fchVencFieldSpecified;
        }
        set {
            this.fchVencFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sii.cl/SiiDte")]
public enum EXPType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("110")]
    Item110,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("111")]
    Item111,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("112")]
    Item112,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesEncabezadoIdDocTipoDespacho {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesEncabezadoIdDocIndServicio {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesEncabezadoIdDocFmaPago {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoIdDocMntPagos {
    
    private System.DateTime fchPagoField;
    
    private string mntPagoField;
    
    private string glosaPagosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchPago {
        get {
            return this.fchPagoField;
        }
        set {
            this.fchPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")]
    public string MntPago {
        get {
            return this.mntPagoField;
        }
        set {
            this.mntPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GlosaPagos {
        get {
            return this.glosaPagosField;
        }
        set {
            this.glosaPagosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sii.cl/SiiDte")]
public enum MedioPagoType {
    
    /// <remarks/>
    CH,
    
    /// <remarks/>
    LT,
    
    /// <remarks/>
    EF,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    TC,
    
    /// <remarks/>
    CF,
    
    /// <remarks/>
    OT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesEncabezadoIdDocTpoCtaPago {
    
    /// <remarks/>
    AHORRO,
    
    /// <remarks/>
    CORRIENTE,
    
    /// <remarks/>
    VISTA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoEmisor {
    
    private string rUTEmisorField;
    
    private string rznSocField;
    
    private string giroEmisField;
    
    private string[] telefonoField;
    
    private string correoEmisorField;
    
    private string[] actecoField;
    
    private string sucursalField;
    
    private string cdgSIISucurField;
    
    private string codAdicSucurField;
    
    private string dirOrigenField;
    
    private string cmnaOrigenField;
    
    private string ciudadOrigenField;
    
    private string cdgVendedorField;
    
    private string idAdicEmisorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RUTEmisor {
        get {
            return this.rUTEmisorField;
        }
        set {
            this.rUTEmisorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RznSoc {
        get {
            return this.rznSocField;
        }
        set {
            this.rznSocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GiroEmis {
        get {
            return this.giroEmisField;
        }
        set {
            this.giroEmisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Telefono", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] Telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CorreoEmisor {
        get {
            return this.correoEmisorField;
        }
        set {
            this.correoEmisorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Acteco", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string[] Acteco {
        get {
            return this.actecoField;
        }
        set {
            this.actecoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sucursal {
        get {
            return this.sucursalField;
        }
        set {
            this.sucursalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CdgSIISucur {
        get {
            return this.cdgSIISucurField;
        }
        set {
            this.cdgSIISucurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodAdicSucur {
        get {
            return this.codAdicSucurField;
        }
        set {
            this.codAdicSucurField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DirOrigen {
        get {
            return this.dirOrigenField;
        }
        set {
            this.dirOrigenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CmnaOrigen {
        get {
            return this.cmnaOrigenField;
        }
        set {
            this.cmnaOrigenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CiudadOrigen {
        get {
            return this.ciudadOrigenField;
        }
        set {
            this.ciudadOrigenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CdgVendedor {
        get {
            return this.cdgVendedorField;
        }
        set {
            this.cdgVendedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdAdicEmisor {
        get {
            return this.idAdicEmisorField;
        }
        set {
            this.idAdicEmisorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoReceptor {
    
    private string rUTRecepField;
    
    private string cdgIntRecepField;
    
    private string rznSocRecepField;
    
    private DTEDefTypeExportacionesEncabezadoReceptorExtranjero extranjeroField;
    
    private string giroRecepField;
    
    private string contactoField;
    
    private string correoRecepField;
    
    private string dirRecepField;
    
    private string cmnaRecepField;
    
    private string ciudadRecepField;
    
    private string dirPostalField;
    
    private string cmnaPostalField;
    
    private string ciudadPostalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RUTRecep {
        get {
            return this.rUTRecepField;
        }
        set {
            this.rUTRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CdgIntRecep {
        get {
            return this.cdgIntRecepField;
        }
        set {
            this.cdgIntRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RznSocRecep {
        get {
            return this.rznSocRecepField;
        }
        set {
            this.rznSocRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoReceptorExtranjero Extranjero {
        get {
            return this.extranjeroField;
        }
        set {
            this.extranjeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GiroRecep {
        get {
            return this.giroRecepField;
        }
        set {
            this.giroRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Contacto {
        get {
            return this.contactoField;
        }
        set {
            this.contactoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CorreoRecep {
        get {
            return this.correoRecepField;
        }
        set {
            this.correoRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DirRecep {
        get {
            return this.dirRecepField;
        }
        set {
            this.dirRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CmnaRecep {
        get {
            return this.cmnaRecepField;
        }
        set {
            this.cmnaRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CiudadRecep {
        get {
            return this.ciudadRecepField;
        }
        set {
            this.ciudadRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DirPostal {
        get {
            return this.dirPostalField;
        }
        set {
            this.dirPostalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CmnaPostal {
        get {
            return this.cmnaPostalField;
        }
        set {
            this.cmnaPostalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CiudadPostal {
        get {
            return this.ciudadPostalField;
        }
        set {
            this.ciudadPostalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoReceptorExtranjero {
    
    private string numIdField;
    
    private string nacionalidadField;
    
    private string idAdicRecepField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NumId {
        get {
            return this.numIdField;
        }
        set {
            this.numIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Nacionalidad {
        get {
            return this.nacionalidadField;
        }
        set {
            this.nacionalidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdAdicRecep {
        get {
            return this.idAdicRecepField;
        }
        set {
            this.idAdicRecepField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoTransporte {
    
    private string patenteField;
    
    private string rUTTransField;
    
    private DTEDefTypeExportacionesEncabezadoTransporteChofer choferField;
    
    private string dirDestField;
    
    private string cmnaDestField;
    
    private string ciudadDestField;
    
    private DTEDefTypeExportacionesEncabezadoTransporteAduana aduanaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Patente {
        get {
            return this.patenteField;
        }
        set {
            this.patenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RUTTrans {
        get {
            return this.rUTTransField;
        }
        set {
            this.rUTTransField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoTransporteChofer Chofer {
        get {
            return this.choferField;
        }
        set {
            this.choferField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DirDest {
        get {
            return this.dirDestField;
        }
        set {
            this.dirDestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CmnaDest {
        get {
            return this.cmnaDestField;
        }
        set {
            this.cmnaDestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CiudadDest {
        get {
            return this.ciudadDestField;
        }
        set {
            this.ciudadDestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoTransporteAduana Aduana {
        get {
            return this.aduanaField;
        }
        set {
            this.aduanaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoTransporteChofer {
    
    private string rUTChoferField;
    
    private string nombreChoferField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RUTChofer {
        get {
            return this.rUTChoferField;
        }
        set {
            this.rUTChoferField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NombreChofer {
        get {
            return this.nombreChoferField;
        }
        set {
            this.nombreChoferField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoTransporteAduana {
    
    private string codModVentaField;
    
    private string codClauVentaField;
    
    private decimal totClauVentaField;
    
    private bool totClauVentaFieldSpecified;
    
    private string codViaTranspField;
    
    private string nombreTranspField;
    
    private string rUTCiaTranspField;
    
    private string nomCiaTranspField;
    
    private string idAdicTranspField;
    
    private string bookingField;
    
    private string operadorField;
    
    private string codPtoEmbarqueField;
    
    private string idAdicPtoEmbField;
    
    private string codPtoDesembField;
    
    private string idAdicPtoDesembField;
    
    private string taraField;
    
    private string codUnidMedTaraField;
    
    private decimal pesoBrutoField;
    
    private bool pesoBrutoFieldSpecified;
    
    private string codUnidPesoBrutoField;
    
    private decimal pesoNetoField;
    
    private bool pesoNetoFieldSpecified;
    
    private string codUnidPesoNetoField;
    
    private string totItemsField;
    
    private string totBultosField;
    
    private DTEDefTypeExportacionesEncabezadoTransporteAduanaTipoBultos[] tipoBultosField;
    
    private decimal mntFleteField;
    
    private bool mntFleteFieldSpecified;
    
    private decimal mntSeguroField;
    
    private bool mntSeguroFieldSpecified;
    
    private string codPaisRecepField;
    
    private string codPaisDestinField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodModVenta {
        get {
            return this.codModVentaField;
        }
        set {
            this.codModVentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodClauVenta {
        get {
            return this.codClauVentaField;
        }
        set {
            this.codClauVentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal TotClauVenta {
        get {
            return this.totClauVentaField;
        }
        set {
            this.totClauVentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotClauVentaSpecified {
        get {
            return this.totClauVentaFieldSpecified;
        }
        set {
            this.totClauVentaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodViaTransp {
        get {
            return this.codViaTranspField;
        }
        set {
            this.codViaTranspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NombreTransp {
        get {
            return this.nombreTranspField;
        }
        set {
            this.nombreTranspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RUTCiaTransp {
        get {
            return this.rUTCiaTranspField;
        }
        set {
            this.rUTCiaTranspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NomCiaTransp {
        get {
            return this.nomCiaTranspField;
        }
        set {
            this.nomCiaTranspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdAdicTransp {
        get {
            return this.idAdicTranspField;
        }
        set {
            this.idAdicTranspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Booking {
        get {
            return this.bookingField;
        }
        set {
            this.bookingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Operador {
        get {
            return this.operadorField;
        }
        set {
            this.operadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodPtoEmbarque {
        get {
            return this.codPtoEmbarqueField;
        }
        set {
            this.codPtoEmbarqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdAdicPtoEmb {
        get {
            return this.idAdicPtoEmbField;
        }
        set {
            this.idAdicPtoEmbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodPtoDesemb {
        get {
            return this.codPtoDesembField;
        }
        set {
            this.codPtoDesembField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdAdicPtoDesemb {
        get {
            return this.idAdicPtoDesembField;
        }
        set {
            this.idAdicPtoDesembField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string Tara {
        get {
            return this.taraField;
        }
        set {
            this.taraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodUnidMedTara {
        get {
            return this.codUnidMedTaraField;
        }
        set {
            this.codUnidMedTaraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PesoBruto {
        get {
            return this.pesoBrutoField;
        }
        set {
            this.pesoBrutoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PesoBrutoSpecified {
        get {
            return this.pesoBrutoFieldSpecified;
        }
        set {
            this.pesoBrutoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodUnidPesoBruto {
        get {
            return this.codUnidPesoBrutoField;
        }
        set {
            this.codUnidPesoBrutoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PesoNeto {
        get {
            return this.pesoNetoField;
        }
        set {
            this.pesoNetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PesoNetoSpecified {
        get {
            return this.pesoNetoFieldSpecified;
        }
        set {
            this.pesoNetoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodUnidPesoNeto {
        get {
            return this.codUnidPesoNetoField;
        }
        set {
            this.codUnidPesoNetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string TotItems {
        get {
            return this.totItemsField;
        }
        set {
            this.totItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string TotBultos {
        get {
            return this.totBultosField;
        }
        set {
            this.totBultosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TipoBultos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesEncabezadoTransporteAduanaTipoBultos[] TipoBultos {
        get {
            return this.tipoBultosField;
        }
        set {
            this.tipoBultosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MntFlete {
        get {
            return this.mntFleteField;
        }
        set {
            this.mntFleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MntFleteSpecified {
        get {
            return this.mntFleteFieldSpecified;
        }
        set {
            this.mntFleteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MntSeguro {
        get {
            return this.mntSeguroField;
        }
        set {
            this.mntSeguroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MntSeguroSpecified {
        get {
            return this.mntSeguroFieldSpecified;
        }
        set {
            this.mntSeguroFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodPaisRecep {
        get {
            return this.codPaisRecepField;
        }
        set {
            this.codPaisRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodPaisDestin {
        get {
            return this.codPaisDestinField;
        }
        set {
            this.codPaisDestinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoTransporteAduanaTipoBultos {
    
    private string codTpoBultosField;
    
    private string cantBultosField;
    
    private string marcasField;
    
    private string idContainerField;
    
    private string selloField;
    
    private string emisorSelloField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CodTpoBultos {
        get {
            return this.codTpoBultosField;
        }
        set {
            this.codTpoBultosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string CantBultos {
        get {
            return this.cantBultosField;
        }
        set {
            this.cantBultosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Marcas {
        get {
            return this.marcasField;
        }
        set {
            this.marcasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdContainer {
        get {
            return this.idContainerField;
        }
        set {
            this.idContainerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Sello {
        get {
            return this.selloField;
        }
        set {
            this.selloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmisorSello {
        get {
            return this.emisorSelloField;
        }
        set {
            this.emisorSelloField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoTotales {
    
    private TipMonType tpoMonedaField;
    
    private decimal mntExeField;
    
    private decimal mntTotalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TipMonType TpoMoneda {
        get {
            return this.tpoMonedaField;
        }
        set {
            this.tpoMonedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MntExe {
        get {
            return this.mntExeField;
        }
        set {
            this.mntExeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MntTotal {
        get {
            return this.mntTotalField;
        }
        set {
            this.mntTotalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sii.cl/SiiDte")]
public enum TipMonType {
    
    /// <remarks/>
    BOLIVAR,
    
    /// <remarks/>
    BOLIVIANO,
    
    /// <remarks/>
    CHELIN,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CORONA DIN")]
    CORONADIN,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CORONA NOR")]
    CORONANOR,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CORONA SC")]
    CORONASC,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("CRUZEIRO REAL")]
    CRUZEIROREAL,
    
    /// <remarks/>
    DIRHAM,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR AUST")]
    DOLARAUST,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR CAN")]
    DOLARCAN,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR HK")]
    DOLARHK,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR NZ")]
    DOLARNZ,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR SIN")]
    DOLARSIN,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR TAI")]
    DOLARTAI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("DOLAR USA")]
    DOLARUSA,
    
    /// <remarks/>
    DRACMA,
    
    /// <remarks/>
    ESCUDO,
    
    /// <remarks/>
    EURO,
    
    /// <remarks/>
    FLORIN,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("FRANCO BEL")]
    FRANCOBEL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("FRANCO FR")]
    FRANCOFR,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("FRANCO SZ")]
    FRANCOSZ,
    
    /// <remarks/>
    GUARANI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LIBRA EST")]
    LIBRAEST,
    
    /// <remarks/>
    LIRA,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("MARCO AL")]
    MARCOAL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("MARCO FIN")]
    MARCOFIN,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("NUEVO SOL")]
    NUEVOSOL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("OTRAS MONEDAS")]
    OTRASMONEDAS,
    
    /// <remarks/>
    PESETA,
    
    /// <remarks/>
    PESO,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("PESO CL")]
    PESOCL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("PESO COL")]
    PESOCOL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("PESO MEX")]
    PESOMEX,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("PESO URUG")]
    PESOURUG,
    
    /// <remarks/>
    RAND,
    
    /// <remarks/>
    RENMINBI,
    
    /// <remarks/>
    RUPIA,
    
    /// <remarks/>
    SUCRE,
    
    /// <remarks/>
    YEN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesEncabezadoOtraMoneda {
    
    private TipMonType tpoMonedaField;
    
    private decimal tpoCambioField;
    
    private bool tpoCambioFieldSpecified;
    
    private decimal mntExeOtrMndaField;
    
    private bool mntExeOtrMndaFieldSpecified;
    
    private decimal mntTotOtrMndaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TipMonType TpoMoneda {
        get {
            return this.tpoMonedaField;
        }
        set {
            this.tpoMonedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal TpoCambio {
        get {
            return this.tpoCambioField;
        }
        set {
            this.tpoCambioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TpoCambioSpecified {
        get {
            return this.tpoCambioFieldSpecified;
        }
        set {
            this.tpoCambioFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MntExeOtrMnda {
        get {
            return this.mntExeOtrMndaField;
        }
        set {
            this.mntExeOtrMndaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MntExeOtrMndaSpecified {
        get {
            return this.mntExeOtrMndaFieldSpecified;
        }
        set {
            this.mntExeOtrMndaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MntTotOtrMnda {
        get {
            return this.mntTotOtrMndaField;
        }
        set {
            this.mntTotOtrMndaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDetalle {
    
    private string nroLinDetField;
    
    private DTEDefTypeExportacionesDetalleCdgItem[] cdgItemField;
    
    private DTEDefTypeExportacionesDetalleIndExe indExeField;
    
    private bool indExeFieldSpecified;
    
    private string nmbItemField;
    
    private string dscItemField;
    
    private decimal qtyRefField;
    
    private bool qtyRefFieldSpecified;
    
    private string unmdRefField;
    
    private decimal prcRefField;
    
    private bool prcRefFieldSpecified;
    
    private decimal qtyItemField;
    
    private bool qtyItemFieldSpecified;
    
    private DTEDefTypeExportacionesDetalleSubcantidad[] subcantidadField;
    
    private System.DateTime fchElaborField;
    
    private bool fchElaborFieldSpecified;
    
    private System.DateTime fchVencimField;
    
    private bool fchVencimFieldSpecified;
    
    private string unmdItemField;
    
    private decimal prcItemField;
    
    private bool prcItemFieldSpecified;
    
    private DTEDefTypeExportacionesDetalleOtrMnda otrMndaField;
    
    private decimal descuentoPctField;
    
    private bool descuentoPctFieldSpecified;
    
    private string descuentoMontoField;
    
    private DTEDefTypeExportacionesDetalleSubDscto[] subDsctoField;
    
    private decimal recargoPctField;
    
    private bool recargoPctFieldSpecified;
    
    private string recargoMontoField;
    
    private DTEDefTypeExportacionesDetalleSubRecargo[] subRecargoField;
    
    private decimal montoItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string NroLinDet {
        get {
            return this.nroLinDetField;
        }
        set {
            this.nroLinDetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CdgItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleCdgItem[] CdgItem {
        get {
            return this.cdgItemField;
        }
        set {
            this.cdgItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleIndExe IndExe {
        get {
            return this.indExeField;
        }
        set {
            this.indExeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndExeSpecified {
        get {
            return this.indExeFieldSpecified;
        }
        set {
            this.indExeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NmbItem {
        get {
            return this.nmbItemField;
        }
        set {
            this.nmbItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DscItem {
        get {
            return this.dscItemField;
        }
        set {
            this.dscItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal QtyRef {
        get {
            return this.qtyRefField;
        }
        set {
            this.qtyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QtyRefSpecified {
        get {
            return this.qtyRefFieldSpecified;
        }
        set {
            this.qtyRefFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UnmdRef {
        get {
            return this.unmdRefField;
        }
        set {
            this.unmdRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PrcRef {
        get {
            return this.prcRefField;
        }
        set {
            this.prcRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrcRefSpecified {
        get {
            return this.prcRefFieldSpecified;
        }
        set {
            this.prcRefFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal QtyItem {
        get {
            return this.qtyItemField;
        }
        set {
            this.qtyItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QtyItemSpecified {
        get {
            return this.qtyItemFieldSpecified;
        }
        set {
            this.qtyItemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Subcantidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleSubcantidad[] Subcantidad {
        get {
            return this.subcantidadField;
        }
        set {
            this.subcantidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchElabor {
        get {
            return this.fchElaborField;
        }
        set {
            this.fchElaborField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FchElaborSpecified {
        get {
            return this.fchElaborFieldSpecified;
        }
        set {
            this.fchElaborFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchVencim {
        get {
            return this.fchVencimField;
        }
        set {
            this.fchVencimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FchVencimSpecified {
        get {
            return this.fchVencimFieldSpecified;
        }
        set {
            this.fchVencimFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UnmdItem {
        get {
            return this.unmdItemField;
        }
        set {
            this.unmdItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PrcItem {
        get {
            return this.prcItemField;
        }
        set {
            this.prcItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrcItemSpecified {
        get {
            return this.prcItemFieldSpecified;
        }
        set {
            this.prcItemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleOtrMnda OtrMnda {
        get {
            return this.otrMndaField;
        }
        set {
            this.otrMndaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal DescuentoPct {
        get {
            return this.descuentoPctField;
        }
        set {
            this.descuentoPctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DescuentoPctSpecified {
        get {
            return this.descuentoPctFieldSpecified;
        }
        set {
            this.descuentoPctFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string DescuentoMonto {
        get {
            return this.descuentoMontoField;
        }
        set {
            this.descuentoMontoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubDscto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleSubDscto[] SubDscto {
        get {
            return this.subDsctoField;
        }
        set {
            this.subDsctoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal RecargoPct {
        get {
            return this.recargoPctField;
        }
        set {
            this.recargoPctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecargoPctSpecified {
        get {
            return this.recargoPctFieldSpecified;
        }
        set {
            this.recargoPctFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string RecargoMonto {
        get {
            return this.recargoMontoField;
        }
        set {
            this.recargoMontoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubRecargo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleSubRecargo[] SubRecargo {
        get {
            return this.subRecargoField;
        }
        set {
            this.subRecargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MontoItem {
        get {
            return this.montoItemField;
        }
        set {
            this.montoItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDetalleCdgItem {
    
    private string tpoCodigoField;
    
    private string vlrCodigoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TpoCodigo {
        get {
            return this.tpoCodigoField;
        }
        set {
            this.tpoCodigoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VlrCodigo {
        get {
            return this.vlrCodigoField;
        }
        set {
            this.vlrCodigoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesDetalleIndExe {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDetalleSubcantidad {
    
    private decimal subQtyField;
    
    private string subCodField;
    
    private string tipCodSubQtyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SubQty {
        get {
            return this.subQtyField;
        }
        set {
            this.subQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SubCod {
        get {
            return this.subCodField;
        }
        set {
            this.subCodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TipCodSubQty {
        get {
            return this.tipCodSubQtyField;
        }
        set {
            this.tipCodSubQtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDetalleOtrMnda {
    
    private decimal prcOtrMonField;
    
    private string monedaField;
    
    private decimal fctConvField;
    
    private bool fctConvFieldSpecified;
    
    private decimal dctoOtrMndaField;
    
    private bool dctoOtrMndaFieldSpecified;
    
    private decimal recargoOtrMndaField;
    
    private bool recargoOtrMndaFieldSpecified;
    
    private decimal montoItemOtrMndaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PrcOtrMon {
        get {
            return this.prcOtrMonField;
        }
        set {
            this.prcOtrMonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Moneda {
        get {
            return this.monedaField;
        }
        set {
            this.monedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal FctConv {
        get {
            return this.fctConvField;
        }
        set {
            this.fctConvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FctConvSpecified {
        get {
            return this.fctConvFieldSpecified;
        }
        set {
            this.fctConvFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal DctoOtrMnda {
        get {
            return this.dctoOtrMndaField;
        }
        set {
            this.dctoOtrMndaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DctoOtrMndaSpecified {
        get {
            return this.dctoOtrMndaFieldSpecified;
        }
        set {
            this.dctoOtrMndaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal RecargoOtrMnda {
        get {
            return this.recargoOtrMndaField;
        }
        set {
            this.recargoOtrMndaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecargoOtrMndaSpecified {
        get {
            return this.recargoOtrMndaFieldSpecified;
        }
        set {
            this.recargoOtrMndaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MontoItemOtrMnda {
        get {
            return this.montoItemOtrMndaField;
        }
        set {
            this.montoItemOtrMndaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDetalleSubDscto {
    
    private DTEDefTypeExportacionesDetalleSubDsctoTipoDscto tipoDsctoField;
    
    private decimal valorDsctoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleSubDsctoTipoDscto TipoDscto {
        get {
            return this.tipoDsctoField;
        }
        set {
            this.tipoDsctoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ValorDscto {
        get {
            return this.valorDsctoField;
        }
        set {
            this.valorDsctoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesDetalleSubDsctoTipoDscto {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("$")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("%")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDetalleSubRecargo {
    
    private DTEDefTypeExportacionesDetalleSubRecargoTipoRecargo tipoRecargoField;
    
    private decimal valorRecargoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDetalleSubRecargoTipoRecargo TipoRecargo {
        get {
            return this.tipoRecargoField;
        }
        set {
            this.tipoRecargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ValorRecargo {
        get {
            return this.valorRecargoField;
        }
        set {
            this.valorRecargoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesDetalleSubRecargoTipoRecargo {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("$")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("%")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesSubTotInfo {
    
    private string nroSTIField;
    
    private string glosaSTIField;
    
    private string ordenSTIField;
    
    private decimal subTotNetoSTIField;
    
    private bool subTotNetoSTIFieldSpecified;
    
    private decimal subTotIVASTIField;
    
    private bool subTotIVASTIFieldSpecified;
    
    private decimal subTotAdicSTIField;
    
    private bool subTotAdicSTIFieldSpecified;
    
    private decimal subTotExeSTIField;
    
    private bool subTotExeSTIFieldSpecified;
    
    private decimal valSubtotSTIField;
    
    private bool valSubtotSTIFieldSpecified;
    
    private string[] lineasDetaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string NroSTI {
        get {
            return this.nroSTIField;
        }
        set {
            this.nroSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GlosaSTI {
        get {
            return this.glosaSTIField;
        }
        set {
            this.glosaSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string OrdenSTI {
        get {
            return this.ordenSTIField;
        }
        set {
            this.ordenSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SubTotNetoSTI {
        get {
            return this.subTotNetoSTIField;
        }
        set {
            this.subTotNetoSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubTotNetoSTISpecified {
        get {
            return this.subTotNetoSTIFieldSpecified;
        }
        set {
            this.subTotNetoSTIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SubTotIVASTI {
        get {
            return this.subTotIVASTIField;
        }
        set {
            this.subTotIVASTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubTotIVASTISpecified {
        get {
            return this.subTotIVASTIFieldSpecified;
        }
        set {
            this.subTotIVASTIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SubTotAdicSTI {
        get {
            return this.subTotAdicSTIField;
        }
        set {
            this.subTotAdicSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubTotAdicSTISpecified {
        get {
            return this.subTotAdicSTIFieldSpecified;
        }
        set {
            this.subTotAdicSTIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SubTotExeSTI {
        get {
            return this.subTotExeSTIField;
        }
        set {
            this.subTotExeSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubTotExeSTISpecified {
        get {
            return this.subTotExeSTIFieldSpecified;
        }
        set {
            this.subTotExeSTIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ValSubtotSTI {
        get {
            return this.valSubtotSTIField;
        }
        set {
            this.valSubtotSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValSubtotSTISpecified {
        get {
            return this.valSubtotSTIFieldSpecified;
        }
        set {
            this.valSubtotSTIFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LineasDeta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string[] LineasDeta {
        get {
            return this.lineasDetaField;
        }
        set {
            this.lineasDetaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesDscRcgGlobal {
    
    private string nroLinDRField;
    
    private DTEDefTypeExportacionesDscRcgGlobalTpoMov tpoMovField;
    
    private string glosaDRField;
    
    private DTEDefTypeExportacionesDscRcgGlobalTpoValor tpoValorField;
    
    private decimal valorDRField;
    
    private decimal valorDROtrMndaField;
    
    private bool valorDROtrMndaFieldSpecified;
    
    private DTEDefTypeExportacionesDscRcgGlobalIndExeDR indExeDRField;
    
    private bool indExeDRFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string NroLinDR {
        get {
            return this.nroLinDRField;
        }
        set {
            this.nroLinDRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDscRcgGlobalTpoMov TpoMov {
        get {
            return this.tpoMovField;
        }
        set {
            this.tpoMovField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GlosaDR {
        get {
            return this.glosaDRField;
        }
        set {
            this.glosaDRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDscRcgGlobalTpoValor TpoValor {
        get {
            return this.tpoValorField;
        }
        set {
            this.tpoValorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ValorDR {
        get {
            return this.valorDRField;
        }
        set {
            this.valorDRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ValorDROtrMnda {
        get {
            return this.valorDROtrMndaField;
        }
        set {
            this.valorDROtrMndaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValorDROtrMndaSpecified {
        get {
            return this.valorDROtrMndaFieldSpecified;
        }
        set {
            this.valorDROtrMndaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesDscRcgGlobalIndExeDR IndExeDR {
        get {
            return this.indExeDRField;
        }
        set {
            this.indExeDRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndExeDRSpecified {
        get {
            return this.indExeDRFieldSpecified;
        }
        set {
            this.indExeDRFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesDscRcgGlobalTpoMov {
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    R,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesDscRcgGlobalTpoValor {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("%")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("$")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesDscRcgGlobalIndExeDR {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DTEDefTypeExportacionesReferencia {
    
    private string nroLinRefField;
    
    private string tpoDocRefField;
    
    private DTEDefTypeExportacionesReferenciaIndGlobal indGlobalField;
    
    private bool indGlobalFieldSpecified;
    
    private string folioRefField;
    
    private string rUTOtrField;
    
    private string idAdicOtrField;
    
    private System.DateTime fchRefField;
    
    private DTEDefTypeExportacionesReferenciaCodRef codRefField;
    
    private bool codRefFieldSpecified;
    
    private string razonRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
    public string NroLinRef {
        get {
            return this.nroLinRefField;
        }
        set {
            this.nroLinRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TpoDocRef {
        get {
            return this.tpoDocRefField;
        }
        set {
            this.tpoDocRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesReferenciaIndGlobal IndGlobal {
        get {
            return this.indGlobalField;
        }
        set {
            this.indGlobalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndGlobalSpecified {
        get {
            return this.indGlobalFieldSpecified;
        }
        set {
            this.indGlobalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FolioRef {
        get {
            return this.folioRefField;
        }
        set {
            this.folioRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RUTOtr {
        get {
            return this.rUTOtrField;
        }
        set {
            this.rUTOtrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdAdicOtr {
        get {
            return this.idAdicOtrField;
        }
        set {
            this.idAdicOtrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime FchRef {
        get {
            return this.fchRefField;
        }
        set {
            this.fchRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DTEDefTypeExportacionesReferenciaCodRef CodRef {
        get {
            return this.codRefField;
        }
        set {
            this.codRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CodRefSpecified {
        get {
            return this.codRefFieldSpecified;
        }
        set {
            this.codRefFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RazonRef {
        get {
            return this.razonRefField;
        }
        set {
            this.razonRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesReferenciaIndGlobal {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DTEDefTypeExportacionesReferenciaCodRef {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}
